# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (16)
# #########################################################################

class AnswerQualityJudgment(BaseModel):
    score: typing.Optional[float] = Field(default=None, description='Answer quality score from 0.0 (completely wrong) to 1.0 (perfect)')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of the score')

class CompressedContext(BaseModel):
    compressed_text: typing.Optional[str] = Field(default=None, description='The compressed context preserving only query-relevant information')

class DiscoveredEntity(BaseModel):
    name: typing.Optional[str] = None
    category: typing.Optional[str] = None
    value: typing.Optional[str] = None
    context: typing.Optional[str] = None

class DiscoveredTable(BaseModel):
    title: typing.Optional[str] = None
    columns: typing.List[str]
    rows: typing.List[typing.Dict[str, str]]

class DocumentSynthesis(BaseModel):
    cross_references: typing.List["SynthesisCrossReference"]
    page_clusters: typing.List["SynthesisPageCluster"]
    document_summary: typing.Optional[str] = None

class HypotheticalDocument(BaseModel):
    passage: typing.Optional[str] = Field(default=None, description='A hypothetical document passage answering the question')

class PageAnalysis(BaseModel):
    description: typing.Optional[str] = None
    entities: typing.List["DiscoveredEntity"]
    tables: typing.List["DiscoveredTable"]
    annotations: typing.List[str]
    page_type: typing.Optional[str] = None

class QueryAnalysis(BaseModel):
    keywords: typing.List[str]
    entity_references: typing.List[str]
    intent: typing.Optional[str] = None
    domain_hint: typing.Optional[str] = None

class QueryVariants(BaseModel):
    variants: typing.List[str] = Field(description='Alternative query formulations')

class RankedChunk(BaseModel):
    index: typing.Optional[int] = None
    score: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

class ReasoningStep(BaseModel):
    text: typing.Optional[str] = Field(default=None, description='The generated reasoning step or final answer')
    is_final: typing.Optional[bool] = Field(default=None, description='True if this is a final answer, false if more reasoning is needed')

class RelevanceJudgment(BaseModel):
    relevant: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None
    needs_clarification: typing.Optional[bool] = None
    clarifying_question: typing.Optional[str] = None
    clarifying_options: typing.Optional[typing.List[str]] = None

class RetrievalNecessityJudgment(BaseModel):
    should_retrieve: typing.Optional[bool] = Field(default=None, description='True if the query requires domain-specific knowledge retrieval')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the judgment from 0.0 to 1.0')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of why retrieval is or is not needed')

class StepBackQuery(BaseModel):
    broader_query: typing.Optional[str] = Field(default=None, description='A broader version of the original question')

class SynthesisCrossReference(BaseModel):
    source_page: typing.Optional[int] = None
    target_page: typing.Optional[int] = None
    relationship: typing.Optional[str] = None
    shared_entities: typing.List[str]

class SynthesisPageCluster(BaseModel):
    pages: typing.List[int]
    reason: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
