# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnswerQualityJudgment": types.AnswerQualityJudgment,
    "stream_types.AnswerQualityJudgment": stream_types.AnswerQualityJudgment,

    "types.CompressedContext": types.CompressedContext,
    "stream_types.CompressedContext": stream_types.CompressedContext,

    "types.DiscoveredEntity": types.DiscoveredEntity,
    "stream_types.DiscoveredEntity": stream_types.DiscoveredEntity,

    "types.DiscoveredTable": types.DiscoveredTable,
    "stream_types.DiscoveredTable": stream_types.DiscoveredTable,

    "types.DocumentSynthesis": types.DocumentSynthesis,
    "stream_types.DocumentSynthesis": stream_types.DocumentSynthesis,

    "types.HypotheticalDocument": types.HypotheticalDocument,
    "stream_types.HypotheticalDocument": stream_types.HypotheticalDocument,

    "types.PageAnalysis": types.PageAnalysis,
    "stream_types.PageAnalysis": stream_types.PageAnalysis,

    "types.QueryAnalysis": types.QueryAnalysis,
    "stream_types.QueryAnalysis": stream_types.QueryAnalysis,

    "types.QueryVariants": types.QueryVariants,
    "stream_types.QueryVariants": stream_types.QueryVariants,

    "types.RankedChunk": types.RankedChunk,
    "stream_types.RankedChunk": stream_types.RankedChunk,

    "types.ReasoningStep": types.ReasoningStep,
    "stream_types.ReasoningStep": stream_types.ReasoningStep,

    "types.RelevanceJudgment": types.RelevanceJudgment,
    "stream_types.RelevanceJudgment": stream_types.RelevanceJudgment,

    "types.RetrievalNecessityJudgment": types.RetrievalNecessityJudgment,
    "stream_types.RetrievalNecessityJudgment": stream_types.RetrievalNecessityJudgment,

    "types.StepBackQuery": types.StepBackQuery,
    "stream_types.StepBackQuery": stream_types.StepBackQuery,

    "types.SynthesisCrossReference": types.SynthesisCrossReference,
    "stream_types.SynthesisCrossReference": stream_types.SynthesisCrossReference,

    "types.SynthesisPageCluster": types.SynthesisPageCluster,
    "stream_types.SynthesisPageCluster": stream_types.SynthesisPageCluster,


}